Graphic chart 86
Kozea/www-media pull request #88
Opened 2021-11-19 16:37 UTC by annabellou

Suite au ticket #86 , quelques changements de style ont été effectués.

Une liste des principaux changements : 

- changement de police,
- adaptation de l'interlignage,
- changements des couleurs,
- suppression de la photo de Guillaume,
- suppression des textes en majuscules,
- changements du logo,
- suppression de la partie actualités (inutilisée).

Reste toujours le problème au survol de la navigation, qui se produit sur Firefox. Ce problème existe depuis bien longtemps, à voir plus tard si on souhaite prendre un peu plus de temps pour le résoudre.

2021-11-22 15:26 UTC, gentooboontoo requested changes

2021-11-22 15:26 UTC, gentooboontoo commented on sass/_variables.sass
> +$bkgd: #F6F7FB
C'est triste que la casse ne soit pas homogène ;) (soit majuscule, soit minuscule)

2021-11-23 08:57 UTC, annabellou commented on sass/_variables.sass
> +$bkgd: #F6F7FB
En effet ! Voilà qui est maintenant harmonisé.

2021-11-23 09:00 UTC, gentooboontoo approved these changes
:+1:

2021-11-23 09:25 UTC, merged